<a href="https://colab.research.google.com/github/stellahrotich/helloworld/blob/master/60minblitzpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Getting Started with PyTorch**

In [0]:
#importing torch library
from __future__ import print_function
import torch



*   List item
*   List item



In [0]:
#construct a  5x3 matrix
x = torch.empty(5,3)
print(x)

tensor([[1.6927e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [0]:
#construct a randomly initialized matric
x = torch.rand(5,3)
print(x)

tensor([[0.8468, 0.7216, 0.4301],
        [0.1638, 0.0348, 0.1028],
        [0.6381, 0.9211, 0.7696],
        [0.8861, 0.2702, 0.1477],
        [0.2395, 0.2558, 0.9962]])


In [0]:
#Construict a matrix filled with zeros
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
#construct a tensor directly form data
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
#create a tensor based on an existing tensor. 
#These methods will reuse properties of the input tensor,
#e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)   
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0559,  0.7545, -1.3120],
        [ 0.2643, -0.9567,  0.7988],
        [-0.4192,  1.1943, -0.6857],
        [ 0.0404,  1.3631, -0.4557],
        [-1.2609,  0.0316,  0.9683]])


In [0]:
#Getting the size of a tensor
print(x.size())

torch.Size([5, 3])


## **Operations on Tensors**

In [0]:
#Addition syntax1
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2149,  1.3841, -0.9026],
        [ 0.5238, -0.6603,  1.1013],
        [ 0.4593,  1.6979, -0.3831],
        [ 0.2627,  2.3185, -0.0737],
        [-0.3637,  0.8428,  1.3279]])


In [0]:
#Addition syntax2
print(torch.add(x, y))

tensor([[-0.2149,  1.3841, -0.9026],
        [ 0.5238, -0.6603,  1.1013],
        [ 0.4593,  1.6979, -0.3831],
        [ 0.2627,  2.3185, -0.0737],
        [-0.3637,  0.8428,  1.3279]])


In [0]:
#Addition: providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[-0.2149,  1.3841, -0.9026],
        [ 0.5238, -0.6603,  1.1013],
        [ 0.4593,  1.6979, -0.3831],
        [ 0.2627,  2.3185, -0.0737],
        [-0.3637,  0.8428,  1.3279]])


In [0]:
#Addition:In place
#Add x to y
y.add_(x)
print(y)

tensor([[-0.2149,  1.3841, -0.9026],
        [ 0.5238, -0.6603,  1.1013],
        [ 0.4593,  1.6979, -0.3831],
        [ 0.2627,  2.3185, -0.0737],
        [-0.3637,  0.8428,  1.3279]])


In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
#To get the value of a tensor as a python number use .item()
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2696])
0.2695715129375458


## **Read on 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers,**

In [0]:
#Converting a torch tensor to NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
#Converting NumPy Arrays to Tensors
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

# **AUTOGRAD:Automatic** **Differentiation**


In [0]:
import torch

In [0]:
#Create a tensor and set requires_grad to be true
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [0]:

#y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [0]:
#.requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. 
#The input flag defaults to False if not given.
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [0]:
print(x.grad)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1079.3850, 1546.2570,  442.3533], grad_fn=<MulBackward0>)


In [0]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [0]:
#stop autograd from tracking history on Tensors with .requires_grad=True by
#wrapping the code block in with torch.no_grad():
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
